# 服务器配置
[server]
port = 8081


# 数据库配置
[database]
path = "data/cesi.db"

# 节点配置 - 测试环境暂时为空
[[nodes]]
name = "local"
environment = "production"
host = "127.0.0.1"
port = 9001
username = "user"
password = "123"


